# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Client-Deployment"
  Client-Deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Check out code
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Client Docker image
        with:
          image: arifibnshabbir/project-management
          tags: client
          registry: docker.io
          # directory: ./client
          dockerfile: ./client/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


  # This workflow contains a single job called "Server-Deployment"
  Server-Deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Check out code
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Server Docker image
        with:
          image: arifibnshabbir/project-management
          tags: server
          registry: docker.io
          # directory: ./client
          dockerfile: ./server/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     buildkitd-flags: --debug
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Build and Push Client Docker Image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./client/Dockerfile
      #     # file: ./client/Dockerfile
      #     push: true
      #     tags: arifibnshabbir/project-management:client
  

      # Runs a single command using the runners shell
      # - name: docker build client
      #   run: |
      #     docker build ./client -t arifibnshabbir/project-management:client

      # # Runs a set of commands using the runners shell
      # - name: docker build server
      #   run: |
      #     docker build ./server -t arifibnshabbir/project-management:server
