# .github/workflows/deploy.yml

name: GitHub Pages

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - '.github/workflows/pages.yml'
#       - 'website/**'
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-20.04
#     permissions:
#       contents: write
#     concurrency:
#       group: ${{ github.workflow }}-${{ github.ref }}
#     defaults:
#       run:
#         working-directory: website
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '17'

#       - name: Get yarn cache
#         id: yarn-cache
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - name: Cache dependencies
#         uses: actions/cache@v2
#         with:
#           path: ${{ steps.yarn-cache.outputs.dir }}
#           key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-website-

#       - run: yarn install --frozen-lockfile
#       - run: yarn build

#       # Popular action to deploy to GitHub Pages:
#       # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
#       - name: Deploy to Github Pages
#         uses: peaceiris/actions-gh-pages@v3
#         # if: ${{ github.ref == 'refs/heads/master' }}
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # publish_branch: gh-pages  # default: gh-pages
#           publish_dir: ./website/build
#           # destination_dir: project-management
#           exclude_assets: '.github,exclude-file1,exclude-file2'
#           commit_message: ${{ github.event.head_commit.message }}
#           allow_empty_commit: true # Allow empty commits
#           # The following lines assign commit authorship to the official
#           # GH-Actions bot for deploys to `gh-pages` branch:
#           # https://github.com/actions/checkout/issues/13#issuecomment-724415212
#           # The GH actions bot is used by default if you didn't specify the two fields.
#           # You can swap them out with your own user credentials.
#           user_name: mdarif
#           user_email: arif_iq@yahoo.co.in


on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: mdarif
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages